name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_verify:
    name: Build and Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
          cache: maven
      
      - name: Verify
        run: mvn -B -U verify
  
  docker_build_and_push:
    name: Build and Push Docker images
    needs: [build_and_verify]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - uses: actions/checkout@v3
      
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
          cache: maven
      
      - name: Setup env variables
        run: |
          echo "DOCKER_REPOSITORY=paprikar/cicd-test" >> $GITHUB_ENV
          BUILD_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
      
      - name: Compile
        run: mvn -B -U compile
      
      - name: Build Docker image
        run: |
          mvn -B -U jib:dockerBuild \
          -Djib.to.image=${{ env.DOCKER_REPOSITORY }} \
          -Djib.to.tags=${{ env.BUILD_VERSION }},latest
      
      - name: Build Docker image (arm32v7)
        run: |
          mvn -B -U jib:dockerBuild \
          -Djib.from.image=arm32v7/adoptopenjdk:11-jre \
          -Djib.from.platforms=linux/arm \
          -Djib.to.image=${{ env.DOCKER_REPOSITORY }} \
          -Djib.to.tags=${{ env.BUILD_VERSION }}-arm32v7,latest-arm32v7
      
      - name: Push to Docker Hub
        run: docker push -a ${{ env.DOCKER_REPOSITORY }}
  
  publish:
    name: Publish
    needs: [build_and_verify]
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
          cache: maven
      
      - name: Publish
        run: mvn -B -U deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
