name: Draft Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: changelog_build
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release
        with:
          body: ${{ steps.changelog_build.outputs.changelog }}
