name: Create Release

on:
  push:
    tags:
      - v*

jobs:
  create:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release
        with:
          body: ${{ steps.github_release.outputs.changelog }}
