name: Push Docker images

on:
  push:
    branches: [ master ]
    paths:
      - src/**
      - pom.xml

jobs:
  docker_build_and_push:
    name: Build and Push Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
          cache: maven

      - name: Setup env variables
        run: |
          echo "DOCKER_REPOSITORY=paprikar/cicd-test" >> $GITHUB_ENV
          BUILD_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV

      - name: Compile
        run: mvn -B -U compile

      - name: Build Docker image
        run: |
          mvn -B -U \
          -Djib.to.image=$DOCKER_REPOSITORY:latest \
          -Djib.to.tags=$BUILD_VERSION \
          jib:dockerBuild

      - name: Push to Docker Hub
        run: docker push -a $DOCKER_REPOSITORY
