name: Release artifacts

on:
  release:
    types: [ published ]

jobs:
  upload_jars:
      name: Upload JARs
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Setup JDK 11
          uses: actions/setup-java@v3
          with:
            distribution: adopt
            java-version: 11
            cache: maven

        - name: Setup env variables
          run: |
            BUILD_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV

        - name: Package
          run: mvn -B -U package
        
        - name: Upload
          uses: softprops/action-gh-release@v1
          with:
            files: target/*.jar

