name: Release artifacts

on:
  push:
    tags:
      - v*
#  release:
#    types: [ published ]

jobs:
  upload_jars:
    name: Upload JARs
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
          cache: maven

      - name: Package
        run: mvn -B -U

      - name: Upload
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: ${{ github.ref_name }} Release
          files: target/*.jar
          automatic_release_tag: ${{ github.ref_name }}
          draft: true
          prerelease: false
          repo_token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Upload
#        uses: softprops/action-gh-release@v1
#        with:
#          name: ${{ github.ref_name }} Release
#          generate_release_notes: true
#          files: target/*.jar
#          draft: true
